// <auto-generated>
//     Generated using the NSwag toolchain v14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>

#pragma warning disable 1591

using System.Text.Json.Serialization;

namespace HyRest.Identity
{
    
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum AccessTokenType
    {
        _0 = 0,
        _1 = 1,
    }
}

#pragma warning restore 1591
