// <auto-generated>
//     Generated using the NSwag toolchain v14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>

#pragma warning disable 1591
#pragma warning disable 8625

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HyRest.Identity
{
    using System = global::System;

    
    public partial class LogoutSettings
    {
        [JsonPropertyName("PostLogoutRedirectUris")]
        public ICollection<string> PostLogoutRedirectUris { get; set; }

        [JsonPropertyName("FrontChannelLogoutUri")]
        public string FrontChannelLogoutUri { get; set; }

        [JsonPropertyName("FrontChannelLogoutSessionRequired")]
        public bool FrontChannelLogoutSessionRequired { get; set; } = true;

        [JsonPropertyName("BackChannelLogoutUri")]
        public string BackChannelLogoutUri { get; set; }

        [JsonPropertyName("BackChannelLogoutSessionRequired")]
        public bool BackChannelLogoutSessionRequired { get; set; } = true;
    }
}

#pragma warning restore 8625
#pragma warning restore 1591
