using System.Text.Json.Serialization;

namespace HyRest.Identity
{
    public partial class ClientSecret
    {
        [JsonPropertyName("IsAutoGenerated")]
        public bool IsAutoGenerated { get; set; }

        [JsonPropertyName("Description")]
        public string Description { get; set; }

        [JsonPropertyName("Value")]
        [System.ComponentModel.DataAnnotations.Required]
        public string Value { get; set; }

        [JsonPropertyName("Expiration")]
        public System.DateTimeOffset? Expiration { get; set; }

        [JsonPropertyName("Type")]
        [System.ComponentModel.DataAnnotations.Required]
        public string Type { get; set; }

        [JsonPropertyName("Hashed")]
        public bool Hashed { get; set; } = true;
    }
}