using HyRest.Utilities;
using System.Text.Json.Serialization;

namespace HyRest.Hyland.IdentityAdministration;

public partial class ClientSecret
{
    [JsonPropertyName("IsAutoGenerated")]
    public bool IsAutoGenerated { get; set; }

    [JsonPropertyName("Description")]
    public string Description { get; set; }

    [JsonPropertyName("Value")]
    [System.ComponentModel.DataAnnotations.Required]
    public string Value { get; set; }

    [JsonPropertyName("Expiration")]
    public DateTimeOffset? Expiration { get; set; }

    [JsonPropertyName("Type")]
    [System.ComponentModel.DataAnnotations.Required]
    [HyRestConverter<JsonStringEnumConverter>]
    public SecretType Type { get; set; } = SecretType.SharedSecret;

    [JsonPropertyName("Hashed")]
    public bool Hashed { get; set; } = true;
}

public enum SecretType
{
    SharedSecret,
    X509Thumbprint,
    X509Name,
    X509Certificate_Base64,
}
