// <auto-generated>
//     Generated using the NSwag toolchain v14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>

#pragma warning disable 1591
#pragma warning disable 8625

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HyRest.Identity
{
    using System = global::System;

    
    public partial class CreateModifyTenant
    {
        [JsonPropertyName("Name")]
        public string Name { get; set; }

        [JsonPropertyName("AdministrativeUsers")]
        public ICollection<string> AdministrativeUsers { get; set; }

        [JsonPropertyName("AdministrativeGroups")]
        public ICollection<string> AdministrativeGroups { get; set; }

        [JsonPropertyName("ManuallyManagedGroups")]
        public ICollection<string> ManuallyManagedGroups { get; set; }

        [JsonPropertyName("Connection")]
        public ConnectionSettings Connection { get; set; }

        [JsonPropertyName("Clients")]
        public ICollection<IdsClient> Clients { get; set; }

        [JsonPropertyName("Providers")]
        public object Providers { get; set; }

        [JsonPropertyName("ApiResources")]
        public ICollection<ApiResource> ApiResources { get; set; }

        [JsonPropertyName("ScimEndpoint")]
        public string ScimEndpoint { get; set; }

        [JsonPropertyName("EnableLocalLogin")]
        public bool EnableLocalLogin { get; set; }
    }
}

#pragma warning restore 8625
#pragma warning restore 1591
