// <auto-generated>
//     Generated using the NSwag toolchain v14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>

#pragma warning disable 1591
#pragma warning disable 8625

using System.Text.Json.Serialization;

namespace HyRest.Identity
{
    using System = global::System;

    /// <summary>Reference to an object with an Id and Name</summary>
    
    public partial class IdNamePair
    {
        /// <summary>Id of the object</summary>
        [JsonPropertyName("Id")]
        public string Id { get; set; }

        /// <summary>Name of the object</summary>
        [JsonPropertyName("Name")]
        public string Name { get; set; }

        /// <summary>Type of the object</summary>
        [JsonPropertyName("Type")]
        public string Type { get; set; }
    }
}

#pragma warning restore 8625
#pragma warning restore 1591
