// <auto-generated>
//     Generated using the NSwag toolchain v14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>

#pragma warning disable 1591
#pragma warning disable 8625

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HyRest.Identity
{
    using System = global::System;

    
    public partial class AuthenticationRestrictionSettings
    {
        [JsonPropertyName("EnableLocalLogin")]
        public bool EnableLocalLogin { get; set; } = true;

        [JsonPropertyName("IdentityProviderRestrictions")]
        public ICollection<string> IdentityProviderRestrictions { get; set; }

        [JsonPropertyName("UserSsoLifetime")]
        public int? UserSsoLifetime { get; set; }

        [JsonPropertyName("AllowOfflineAccess")]
        public bool AllowOfflineAccess { get; set; } = false;

        [JsonPropertyName("AllowAccessTokensViaBrowser")]
        public bool AllowAccessTokensViaBrowser { get; set; } = false;

        [JsonPropertyName("AllowedGrantTypes")]
        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.MinLength(1)]
        public ICollection<string> AllowedGrantTypes { get; set; } = new System.Collections.ObjectModel.Collection<string>();

        [JsonPropertyName("AllowedScopes")]
        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.MinLength(1)]
        public ICollection<string> AllowedScopes { get; set; } = new System.Collections.ObjectModel.Collection<string>();
    }
}

#pragma warning restore 8625
#pragma warning restore 1591
