// <auto-generated>
//     Generated using the NSwag toolchain v14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>

#pragma warning disable 1591

using System.Text.Json.Serialization;

namespace HyRest.Identity
{
    using System = global::System;

    
    public partial class PkceSettings
    {
        [JsonPropertyName("RequirePkce")]
        public bool RequirePkce { get; set; } = false;

        [JsonPropertyName("AllowPlainTextPkce")]
        public bool AllowPlainTextPkce { get; set; } = false;
    }
}

#pragma warning restore 1591
