// <auto-generated>
//     Generated using the NSwag toolchain v14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>

#pragma warning disable 1591
#pragma warning disable 8625

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HyRest.Identity
{
    using System = global::System;

    
    public partial class SecuritySettings
    {
        [JsonPropertyName("AllowedCorsOrigins")]
        public ICollection<string> AllowedCorsOrigins { get; set; }
    }
}

#pragma warning restore 8625
#pragma warning restore 1591
