// <auto-generated>
//     Generated using the NSwag toolchain v14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>

#pragma warning disable 1591
#pragma warning disable 8625

using System.Text.Json.Serialization;

namespace HyRest.Identity
{
    using System = global::System;

    
    public partial class TokenSettings
    {
        [JsonPropertyName("IdentityTokenLifetime")]
        public int IdentityTokenLifetime { get; set; } = 300;

        [JsonPropertyName("AccessTokenLifetime")]
        public int AccessTokenLifetime { get; set; } = 3600;

        [JsonPropertyName("UseAccessTokenLifetimeForUserSystemId")]
        public bool UseAccessTokenLifetimeForUserSystemId { get; set; } = false;

        [JsonPropertyName("AuthorizationCodeLifetime")]
        public int AuthorizationCodeLifetime { get; set; } = 300;

        [JsonPropertyName("AbsoluteRefreshTokenLifetime")]
        public int AbsoluteRefreshTokenLifetime { get; set; } = 2592000;

        [JsonPropertyName("SlidingRefreshTokenLifetime")]
        public int SlidingRefreshTokenLifetime { get; set; } = 1296000;

        [JsonPropertyName("RefreshTokenUsage")]
        public TokenUsage RefreshTokenUsage { get; set; }

        [JsonPropertyName("UpdateAccessTokenClaimsOnRefresh")]
        public bool UpdateAccessTokenClaimsOnRefresh { get; set; } = false;

        [JsonPropertyName("RefreshTokenExpiration")]
        public TokenExpiration RefreshTokenExpiration { get; set; }

        [JsonPropertyName("AccessTokenType")]
        public AccessTokenType AccessTokenType { get; set; }

        [JsonPropertyName("IncludeJwtId")]
        public bool IncludeJwtId { get; set; } = false;

        [JsonPropertyName("PairWiseSubjectSalt")]
        public string PairWiseSubjectSalt { get; set; }

        [JsonPropertyName("AlwaysIncludeUserClaimsInIdToken")]
        public bool AlwaysIncludeUserClaimsInIdToken { get; set; } = false;
    }
}

#pragma warning restore 8625
#pragma warning restore 1591
