
using System.Text.Json.Serialization;

namespace HyRest.API.Models;

/// <summary>
/// The  ;a href="https://tools.ietf.org/html/rfc7807"&gt;Problem Detail ;/a&gt;
/// <br/>format defines a way to carry machine-readable details of errors in a
/// <br/>HTTP response to avoid the need to define new error response formats for
/// <br/>HTTP APIs.
/// <br/>
/// <br/>Problem details can be extended and defined for specific
/// <br/>problem types.
/// </summary>
public partial class ProblemDetail
{

    /// <summary>
    /// An absolute URI that identifies the problem type.  When
    /// <br/>dereferenced, it should provide human-readable documentation
    /// <br/>for the problem type (e.g., using HTML).
    /// </summary>
    [JsonPropertyName("type")]
    public System.Uri Type { get; set; }

    /// <summary>
    /// A short, human-readable summary of the problem type. It should
    /// <br/>not change from occurrence to occurrence of the problem.
    /// </summary>
    [JsonPropertyName("title")]
    public string Title { get; set; }

    /// <summary>
    /// The HTTP status code generated by the origin server for this
    /// <br/>occurrence of the problem.
    /// </summary>
    [JsonPropertyName("status")]
    [System.ComponentModel.DataAnnotations.Range(100, 599)]
    public int Status { get; set; }

    /// <summary>
    /// A human readable explanation specific to this occurrence of the
    /// <br/>problem.
    /// </summary>
    [JsonPropertyName("detail")]
    public string Detail { get; set; }

    /// <summary>
    /// A URI reference that identifies the specific occurrence of
    /// <br/>the problem.  It may or may not yield further information
    /// <br/>if dereferenced.
    /// </summary>
    [JsonPropertyName("instance")]
    public System.Uri Instance { get; set; }

    private IDictionary<string, object> _additionalProperties;

    [JsonExtensionData]
    public IDictionary<string, object> AdditionalProperties
    {
        get { return _additionalProperties ?? (_additionalProperties = new Dictionary<string, object>()); }
        set { _additionalProperties = value; }
    }

}

/// <summary>
/// The generic type with a discriminator property, which is an object type name
/// <br/>that is used to differentiate between other schemas which may satisfy
/// <br/>the payload description.
/// </summary>

public partial class DiscriminatorObject : HylandBase
{

    /// <summary>
    /// The object type of the schema specified for the request body or used for the response payload.          
    /// </summary>
    [JsonPropertyName("objectType")]
    public string? ObjectType { get; set; }
}



internal class DateFormatConverter : JsonConverter<System.DateTimeOffset>
{
    public override System.DateTimeOffset Read(ref System.Text.Json.Utf8JsonReader reader, System.Type typeToConvert, System.Text.Json.JsonSerializerOptions options)
    {
        var dateTime = reader.GetString();
        if (dateTime == null)
        {
            throw new System.Text.Json.JsonException("Unexpected JsonTokenType.Null");
        }

        return System.DateTimeOffset.Parse(dateTime);
    }

    public override void Write(System.Text.Json.Utf8JsonWriter writer, System.DateTimeOffset value, System.Text.Json.JsonSerializerOptions options)
    {
        writer.WriteStringValue(value.ToString("yyyy-MM-dd"));
    }
}