
using System.Text.Json.Serialization;

namespace HyRest.API.Models;

/// <summary>
/// A collection of LockInfo objects.
/// </summary>
public partial class LockInfoCollectionModel : OnBaseItemCollection<LockInfoModel>
{

}
/// <summary>
/// Information on a lock that has been put on an item.
/// </summary>
public partial class LockInfoModel : OnBaseItem
{
    [JsonIgnore]
    private new string Id { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }

    /// <summary>
    /// A unique identifier of the user that holds the lock on this item.
    /// </summary>
    [JsonPropertyName("lockedByUserId")]
    public string LockedByUserId { get; set; }

    [JsonPropertyName("lockType")]
    public LockType LockType { get; set; }

    [JsonPropertyName("currentLock")]
    public DocumentLockStatus CurrentLock { get; set; }
}


/// <summary>
/// The  ;a href="https://tools.ietf.org/html/rfc7807"&gt;Problem Detail ;/a&gt;
/// <br/>format defines a way to carry machine-readable details of errors in a
/// <br/>HTTP response to avoid the need to define new error response formats for
/// <br/>HTTP APIs.
/// <br/>
/// <br/>Problem details can be extended and defined for specific
/// <br/>problem types.
/// </summary>
public partial class ProblemDetailLockingError : HylandBase
{

    /// <summary>
    /// An absolute URI that identifies the problem type.  When
    /// <br/>dereferenced, it should provide human-readable documentation
    /// <br/>for the problem type (e.g., using HTML).
    /// </summary>
    [JsonPropertyName("type")]
    public System.Uri Type { get; set; }

    /// <summary>
    /// A short, human-readable summary of the problem type. It should
    /// <br/>not change from occurrence to occurrence of the problem.
    /// </summary>
    [JsonPropertyName("title")]
    public string Title { get; set; }

    /// <summary>
    /// The HTTP status code generated by the origin server for this
    /// <br/>occurrence of the problem.
    /// </summary>
    [JsonPropertyName("status")]
    [System.ComponentModel.DataAnnotations.Range(100, 599)]
    public int Status { get; set; }

    /// <summary>
    /// A human readable explanation specific to this occurrence of the
    /// <br/>problem.
    /// </summary>
    [JsonPropertyName("detail")]
    public string Detail { get; set; }

    /// <summary>
    /// A URI reference that identifies the specific occurrence of
    /// <br/>the problem.  It may or may not yield further information
    /// <br/>if dereferenced.
    /// </summary>
    [JsonPropertyName("instance")]
    public System.Uri Instance { get; set; }

    [JsonPropertyName("lockInfo")]
    public LockInfoModel LockInfo { get; set; }

}

